### ISSUE TITLE
Push your most current work!

### ISSUE THREAD

**Issue by timsamoff** [APUGames/firestone-platformer#3]
Please remember to push your latest work -- the last push was two weeks ago.

**Comment by Ghost-Beans** [comment]
My files will not push because of an error that GitKraken shows as Invalid remote name 'origin' in my files [it has a file path to show as well]. I looked through my files and could not find this. I have looked online and cannot understand how to solve this.

**Comment by Ghost-Beans** [comment]
the highlighted part in the above comment is supposed to be in parentheses, but is switched to a hyperlink, pay it no mind

**Comment by Ghost-Beans** [comment]
Pushed files
